version: '3.3'
services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/server
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./server/.env

  db:
    image: postgres:12.4-alpine
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'