# Generated by Django 4.1.1 on 2022-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_genre_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='book',
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('plus', 'Плюс'), ('premium', 'Премиум')], default='standart', max_length=8),
            preserve_default=False,
        ),
    ]
