# Generated by Django 4.1.1 on 2022-09-25 08:45

import books.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_subscription_book_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='text',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='description', verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='upload',
            field=models.FileField(default=None, upload_to=books.utils.author_directory_path),
            preserve_default=False,
        ),
    ]
