# Generated by Django 4.1.1 on 2022-09-25 08:45

import books.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_text_book_description_book_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upload',
            field=models.FileField(default='', upload_to=books.utils.author_directory_path),
        ),
    ]
