# Generated by Django 4.1.1 on 2022-09-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
