# Generated by Django 4.1.1 on 2022-09-28 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0012_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subscription_type',
            field=models.CharField(choices=[(1, 'Стандарт'), (2, 'Плюс'), (3, 'Премиум')], max_length=8, verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(choices=[(3, '3 Месяца'), (6, '6 Месяцев'), (12, 'Год')], verbose_name='Длительность подписки в месяцах'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[(1, 'Стандарт'), (2, 'Плюс'), (3, 'Премиум')], max_length=8, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
