# Generated by Django 4.1.1 on 2022-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_subscription_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subscription_type',
            field=models.IntegerField(choices=[(1, 'Стандарт'), (2, 'Плюс'), (3, 'Премиум')], verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(1, 'Стандарт'), (2, 'Плюс'), (3, 'Премиум')], verbose_name='Тип'),
        ),
    ]
