# Generated by Django 4.1.1 on 2022-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_like_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subscription_type',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('plus', 'Плюс'), ('premium', 'Премиум')], default='standart', max_length=8),
            preserve_default=False,
        ),
    ]
